---
- name: Linux Patching playbook
  hosts: all
  gather_facts: true
  vars:
    check_reachability: true

  tasks:

    - name: Ping then patch
      ansible.builtin.import_tasks: './patch_linux_ping.yml'
      when: check_reachability


    - name: Don't Ping, just patch
      ansible.builtin.import_tasks: './patch_linux_no_ping.yml'
      when: not check_reachability
